hour_a = abs(int(input())) 
minutes_a = abs(int(input())) 
seconds_a = abs(int(input()))  
hour_b = abs(int(input())) 
minutes_b = abs(int(input())) 
seconds_b = abs(int(input()))
time_a = (hour_a * 3600) + (minutes_a * 60) + (seconds_a * 1)
time_b = (hour_b * 3600) + (minutes_b * 60) + (seconds_b * 1)
print( time_b - time_a )
